import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    dietFilters: [
      {code: 1, label: 'Gluten-free', name: 'gluten-free', selected: false},
      {code: 2, label: 'Vegan', name: 'vegan', selected: false},
      {code: 3, label: 'Sugar-conscious', name: 'sugar-conscious', selected: false},
      {code: 4, label: 'Raw', name: 'raw', selected: false},
      {code: 5, label: 'Organic', name: 'organic', selected: false},
      {code: 6, label: 'Vegetarian', name: 'vegetarian', selected: false},
      {code: 7, label: 'Dairy-free', name: 'dairy-free', selected: false},
      {code: 8, label: 'High Protein', name: 'high-protein', selected: false},
      {code: 9, label: 'Preservative-free', name: 'preservative-free', selected: false},
      {code: 10, label: 'GMO-free', name: 'gmo-free', selected: false},
    ],
    tags: [
      {code: 1, label: 'Meal Solutions', name: 'meals', selected: false},
      {code: 2, label: 'Breakfast Solutions', name: 'breakfast', selected: false},
      {code: 3, label: 'Pantry Essentials', name: 'essentials', selected: false},
      {code: 4, label: 'Snacks', name: 'snacks', selected: false},
      {code: 5, label: 'Sweet Snacks', name: 'sweet-snacks', selected: false},
      {code: 6, label: 'Fresh Produce', name: 'fresh-produce', selected: false},
      {code: 7, label: 'Condiments & oils', name: 'condiments-oils', selected: false},
      {code: 8, label: 'Drinks', name: 'drinks', selected: false},
      {code: 9, label: 'Reduced sugar', name: 'sugar-conscious', selected: false},
      {code: 10, label: 'Raw', name: 'raw', selected: false},
      {code: 11, label: 'Eco friendly', name: 'eco-friendly', selected: false},
      {code: 11, label: 'Sugar Free', name: 'sugar-free', selected: false}
    ],
    homeCards: [
      {
        id: 1,
        cardProportion: 85,
        hasImage: true,
        hasCTA: true,
        imagePath: `meals.jpg`,
        headerText: `meal solutions`,
        subheaderText: `Our selection of convenient vegan and vegetarian meals is packed with flavour and goodness. Browse our selection to enjoy a fuss-free meal perfect for lunch or dinner.`,
        category: 'meals'
      },
      {
        id: 2,
        cardProportion: 85,
        hasImage: true,
        hasCTA: true,
        imagePath: `breakfast.jpg`,
        headerText: `BREAKFAST SOLUTIONS`,
        subheaderText: `Kick-start your day with a nutritious and tasty breakfast, with none of the guilt. Discover our healthier options to satisfy your palate and lifestyle needs.`,
        category: 'breakfast'
      },
      {
        id: 3,
        cardProportion: 85,
        hasCTA: true,
        hasImage: true,
        imagePath: `essentials.jpg`,
        headerText: `pantry essentials`,
        subheaderText: `Keep your pantry stocked with the best assortment of raw, organic and gluten-free products at supermarket prices. Our selection includes pasta, raw honey and more.`,
        category: 'essentials'
      },
      {
        id: 4,
        cardProportion: 85,
        hasImage: true,
        hasCTA: true,
        imagePath: `snacks.jpg`,
        headerText: `snacks`,
        subheaderText: `Healthy snacking is easier when you have tasty treats like these. Browse our variety of snacks that are simple, delicious and will easily complement your diet and lifestyle.`,
        category: 'snacks'
      },
      {
        id: 5,
        cardProportion: 85,
        hasImage: true,
        hasCTA: true,
        imagePath: `sweet-snacks.jpg`,
        headerText: `SWEET SNACKS & DESSERTS`,
        subheaderText: `Treat your taste buds without compromising on nutrition with delicious snacks and desserts. Choose from reduced sugar, gluten free, vegan options and more.`,
        category: 'sweet-snacks'

      },
      {
        id: 6,
        cardProportion: 85,
        hasImage: true,
        hasCTA: true,
        imagePath: `drinks.jpg`,
        headerText: `drinks`,
        subheaderText: `Quench your thirst with great-tasting refreshments perfectly suited to your lifestyle requirements. Your choices include organic, sugar free and more.`,
        category: 'drinks'
      },
      {
        id: 7,
        cardProportion: 85,
        hasImage: true,
        hasCTA: true,
        imagePath: `condiments.jpg`,
        headerText: `condiments & oils`,
        subheaderText: `For cooking, baking and roasting – there's no better choice! Our selection includes products which are unrefined, have no added preservatives and reduced sugar.`,
        category: 'condiments-oils'
      },
      {
        id: 8,
        cardProportion: 85,
        hasImage: true,
        hasCTA: true,
        imagePath: `cleaning.jpg`,
        headerText: `ECO-FRIENDLY CLEANING PRODUCTS`,
        subheaderText: `Our range of affordable cleaning products is eco-friendly, cruelty-free and made with biodegradable materials.`,
        category: 'eco-friendly'
      }
    ],
    productCards: [
      {
        id: 1,
        cardProportion: 127.5,
        imagePath: 'almonds_mint.png',
        imagePathThumbnail: 'almonds_mint.jpg',
        flash: 'new',
        tags: ['vegan', 'vegetarian', 'sugar-conscious'],
        productName: 'Skinny Dipped Roasted Almonds (Mint)',
        description: 'Simple Truth Skinny Dipped Roasted Almonds with mint-flavoured Belgian dark chocolate are guilt-free treats that are made with reduced sugar.',
        nutritionalInfo: ['Reduced sugar',
          'No added preservatives',
          'Belgian chocolate',
          'High in fibre',
          'No artificial colours or flavours'
        ]
      },
      {
        id: 2,
        cardProportion: 127.5,
        imagePath: 'almonds_plain.png',
        imagePathThumbnail: 'almonds_plain.jpg',
        flash: 'new',
        tags: ['vegan', 'vegetarian', 'sugar-conscious'],
        productName: 'Skinny Dipped Roasted Almonds (Dark Chocolate)',
        description: 'Simple Truth Skinny Dipped Roasted Almonds with dark Belgian chocolate are guilt-free treats that are made with reduced sugar.',
        nutritionalInfo: ['Reduced sugar',
          'No added preservatives',
          'Belgian chocolate',
          'High in fibre',
          'No artificial colours or flavours'
        ]
      },
      {
        id: 3,
        cardProportion: 127.5,
        imagePath: 'almonds_raspberry.png',
        imagePathThumbnail: 'almonds_raspberry.jpg',
        flash: 'new',
        tags: ['vegan', 'vegetarian', 'sugar-conscious'],
        productName: 'Skinny Dipped Roasted Almonds (Raspberry)',
        description: 'Simple Truth Skinny Dipped Roasted Almonds are delicious, guilt-free and made with raspberry-flavoured Belgian dark chocolate.',
        nutritionalInfo: ['Reduced sugar',
          'No added preservatives',
          'Belgian chocolate',
          'High in fibre',
          'No artificial colours or flavours'
        ]
      },
      {
        id: 4,
        cardProportion: 127.5,
        imagePath: 'almonds_slated_caramel.png',
        imagePathThumbnail: 'almonds_slated_caramel.jpg',
        flash: 'new',
        tags: ['vegan', 'vegetarian', 'sugar-conscious'],
        productName: 'Skinny Dipped Roasted Almonds (Salted Caramel) ',
        description: 'Simple Truth Skinny Dipped Roasted Almonds with salted caramel-flavoured dark Belgian chocolate are guilt-free treats that are made with reduced sugar.',
        nutritionalInfo: ['Reduced sugar',
          'No added preservatives',
          'Belgian chocolate',
          'High in fibre',
          'No artificial colours or flavours'
        ]
      },
      {
        id: 5,
        cardProportion: 127.5,
        imagePath: 'apple_cider_vinegar.png',
        imagePathThumbnail: 'apple_cider_vinegar.jpg',
        flash: 'new',
        tags: ['organic'],
        productName: 'Raw & Unfiltered Apple Cider Vinegar',
        description: 'Simple Truth Raw & Unfiltered Apple Cider Vinegar is a must-have in every home. This versatile product is organic, raw and contains nothing but apples.',
        nutritionalInfo: ['3100% natural',
          'Nothing but apples',
          'Unpasteurised',
          'Organic',
          'Raw',
          'Unfiltered'
        ]
      },
      {
        id: 6,
        cardProportion: 127.5,
        imagePath: 'asian_bowl.png',
        imagePathThumbnail: 'asian_bowl.jpg',
        flash: 'new',
        tags: ['vegan', 'meals'],
        productName: 'Asian bowl',
        description: 'For a burst of Asian-inspired flavour, choose this vegan Simple Truth Asian Bowl. It has no added MSG and is high in fibre.',
        nutritionalInfo: ['Source of fibre', 'No added preservatives']
      },
      {
        id: 7,
        cardProportion: 127.5,
        imagePath: 'bar_coconut_lemon.png',
        imagePathThumbnail: 'bar_coconut_lemon.jpg',
        flash: 'new',
        tags: ['vegan', 'sweet-snacks', 'sugar-conscious'],
        productName: 'Coconut & Lemon Bar ',
        description: 'The Simple Truth Coconut & Lemon Bar is vegan, made with dates and contains no added sugar. Find this great snack in-store now.',
        nutritionalInfo: ['No added preservatives',
          'No added sugar',
          'With dates',
          'High in fibre',
          'No artificial colours or flavours']
      },
      {
        id: 8,
        cardProportion: 127.5,
        imagePath: 'bar_raw_pecan_salted_caramel.png',
        imagePathThumbnail: 'bar_raw_pecan_salted_caramel.jpg',
        flash: 'new',
        tags: ['raw', 'sweet-snacks', 'preservative-free', 'sugar-conscious'],
        productName: 'Raw Pecan & Salted Caramel Flavoured Bar ',
        description: 'The Simple Truth Raw Pecan & Salted Caramel Flavoured Bar is vegan, made with dates and contains no added sugar. Find this great snack in-store now.',
        nutritionalInfo: ['Raw',
          'No added preservatives',
          'No added sugar',
          'With dates',
          'Source of fibre',
          'No artificial colours or flavours']
      },
      {
        id: 9,
        cardProportion: 127.5,
        imagePath: 'brown_rice_crackers_black_white_sesame.png',
        imagePathThumbnail: 'brown_rice_crackers_black_white_sesame.jpg',
        flash: 'new',
        tags: ['gluten-free', 'snacks', 'preservative-free', 'gmo-free'],
        productName: 'Brown Rice Crackers with Black & White Sesame Seeds',
        description: 'For a delicious high-fibre snack, try Simple Truth Brown Rice Crackers with Black and White Sesame Seeds. These crackers are baked, not fried, and available in-store now.',
        nutritionalInfo: ['Wholegrain',
          'Trans fat free',
          'Baked not fried',
          'High in fibre',
          'No added preservatives',
          'GMO free']
      },
      {
        id: 10,
        cardProportion: 127.5,
        imagePath: 'brown_rice_crackers_flaxseed_sesame.png',
        imagePathThumbnail: 'brown_rice_crackers_flaxseed_sesame.jpg',
        flash: 'new',
        tags: ['gluten-free', 'snacks', 'preservative-free', 'gmo-free'],
        productName: 'Simple Truth Brown Rice Crackers with Flaxseed & Black Sesame Seeds',
        description: 'For a delicious high-fibre snack, try Simple Truth Brown Rice Crackers with Flaxseed and Black Sesame Seeds. These crackers are baked, not fried, and available in-store now.',
        nutritionalInfo: ['Wholegrain',
          'Trans fat free',
          'Baked not fried',
          'High in fibre',
          'No added preservatives',
          'GMO free']
      },
      {
        id: 11,
        cardProportion: 127.5,
        imagePath: 'brown_rice_crackers_sea_salt.png',
        imagePathThumbnail: 'brown_rice_crackers_sea_salt.jpg',
        flash: 'new',
        tags: ['gluten-free', 'preservative-free', 'gmo-free', 'snacks'],
        productName: 'Brown Rice Crackers with Sea Salt',
        description: 'For a delicious high-fibre snack, try Simple Truth Brown Rice Crackers with Sea Salt. These crackers are baked, not fried, and available in-store now.',
        nutritionalInfo: ['Wholegrain',
          'Trans fat free',
          'Baked not fried',
          'High in fibre ',
          'No added preservatives',
          'GMO free']
      },
      {
        id: 12,
        cardProportion: 127.5,
        imagePath: 'buttermilk_rusks.png',
        imagePathThumbnail: 'buttermilk_rusks.jpg',
        flash: 'new',
        tags: ['gluten-free', 'sugar-conscious', 'breakfast'],
        productName: 'BUTTERMILK RUSKS',
        description: 'Buttermilk Rusks are a South African favourite and now you can enjoy this Simple Truth treat which is made by hand and is gluten free.',
        nutritionalInfo: ['30% reduced sugar', 'Source of fibre', 'Lacto-ovo-vegetarian', 'No added preservatives']
      },
      {
        id: 13,
        cardProportion: 127.5,
        imagePath: 'cheese_cheddar.png',
        imagePathThumbnail: 'cheese_cheddar.jpg',
        flash: 'new',
        tags: ['fresh-produce', 'vegetarian'],
        productName: 'Lactose Free Cheddar',
        description: 'Simple Truth Lactose Free Cheddar is a source of calcium with no added flavours and is lacto-vegetarian too.',
        nutritionalInfo: ['Lacto-vegetarian',
          'Source of calcium',
          'No artificial colours',
          'No added flavours'
        ]
      },
      {
        id: 14,
        cardProportion: 127.5,
        imagePath: 'cheese_gouda.png',
        imagePathThumbnail: 'cheese_gouda.jpg',
        flash: 'new',
        tags: ['fresh-produce', 'vegetarian'],
        productName: 'Simple Truth Gouda Cheese',
        description: 'Simple Truth Lactose Free Gouda is a source of calcium with no added flavours and is lacto-vegetarian too.',
        nutritionalInfo: ['Lacto-vegetarian',
          'Source of calcium',
          'No artificial colours',
          'No added flavours'
        ]
      },
      {
        id: 15,
        cardProportion: 127.5,
        imagePath: 'chipotle_sauce.png',
        imagePathThumbnail: 'chipotle_sauce.jpg',
        flash: 'new',
        tags: ['condiments-oils', 'vegan', 'sugar-conscious'],
        productName: 'Chipotle Sauce',
        description: 'Give your meals a hint of spice and deep flavour with Simple Truth Chipotle Sauce. This sauce is vegan, contains no added sugar or preservatives.',
        nutritionalInfo: [
          'No added MSG',
          'No artificial colours or flavours',
          'No added preservatives'
        ]
      },
      {
        id: 16,
        cardProportion: 127.5,
        imagePath: 'choc_chip_shortbread.png',
        imagePathThumbnail: 'choc_chip_shortbread.jpg',
        flash: 'new',
        tags: ['gluten-free', 'sweet-snacks', 'preservative-free'],
        productName: 'Choc Chip Shortbread',
        description: 'Simple Truth Choc Chip Shortbread is gluten free and made by hand. It has no added preservatives and reduced sugar.',
        nutritionalInfo: ['Reduced sugar',
          'No artificial colours or flavours',
          'No added preservatives',
          'Lacto-vegetarian']
      },
      {
        id: 17,
        cardProportion: 127.5,
        imagePath: 'coconut_sugar.png',
        imagePathThumbnail: 'coconut_sugar.jpg',
        flash: 'new',
        tags: ['condiments-oils', 'vegan'],
        productName: 'Coconut Oil Spray ',
        description: 'The new Simple Truth Refined Coconut Oil Spray is vegan and is ideal for baking, frying and roasting. ',
        nutritionalInfo: ['Made with only coconut oil',
          'Vegan',
          'Deodorised'
        ]
      },
      {
        id: 18,
        cardProportion: 127.5,
        imagePath: 'coconut-water.png',
        imagePathThumbnail: 'coconut-water.jpg',
        flash: 'new',
        tags: ['drinks', 'organic'],
        productName: 'Coconut Water',
        description: 'Simple Truth Coconut Water is made from organic young green coconuts and is sustainably farmed.',
        nutritionalInfo: ['100% pure',
          'Sustainably farmed'
        ]
      },
      {
        id: 19,
        cardProportion: 127.5,
        imagePath: 'vanilla_shortbread.png',
        imagePathThumbnail: 'vanilla_shortbread.jpg',
        flash: 'new',
        tags: ['sweet-snacks', 'gluten-free', 'vegetarian'],
        productName: 'Vanilla Shortbread',
        description: 'Simple Truth Vanilla Shortbread is gluten free and made by hand. It has no added preservatives and reduced sugar.',
        nutritionalInfo: ['Reduced sugar',
          'No artificial colours or flavours',
          'No added preservatives',
          'Lacto-vegetarian']
      },
      {
        id: 20,
        cardProportion: 127.5,
        imagePath: 'cookies_choc_chip.png',
        imagePathThumbnail: 'cookies_choc_chip.jpg',
        flash: 'new',
        tags: ['sweet-snacks', 'gluten-free', 'sugar-conscious', 'vegetarian'],
        productName: 'Double Choc Chip Cookies ',
        description: 'Simple Truth Double Choc Chip Cookies are made with butter and coconut oil. These cookies have reduced sugar, no added salt and are a source of fibre.',
        nutritionalInfo: ['Reduced sugar',
          'Source of fibre',
          'No added salt',
          'No artificial colours or flavours',
          'Wheat free',
          'Lacto-ovo vegetarian'
        ]
      },
      {
        id: 21,
        cardProportion: 127.5,
        imagePath: 'cookies_coconut.png',
        imagePathThumbnail: 'cookies_coconut.jpg',
        flash: 'new',
        tags: ['sugar-conscious', 'sweet-snacks'],
        productName: 'Coconut Cookies',
        description: 'Simple Truth Coconut Cookies are made with butter and coconut oil. This treat has reduced sugar, no added salt and is high in fibre.',
        nutritionalInfo: ['Reduced sugar',
          'High in fibre',
          'No added salt',
          'Made with butter & coconut oil',
          'No artificial colours or flavours']
      },
      {
        id: 22,
        cardProportion: 127.5,
        imagePath: 'cookies_crunchies.png',
        imagePathThumbnail: 'cookies_crunchies.jpg',
        flash: 'new',
        tags: ['sugar-conscious', 'sweet-snacks'],
        productName: 'Oat Crunchies',
        description: 'Simple Truth Oat Crunchies are made with butter and coconut oil. This snack has reduced sugar, no added salt and is high in fibre.',
        nutritionalInfo: ['Reduced sugar',
          'High in fibre',
          'No added salt',
          'Made with butter & coconut oil',
          'No artificial colours or flavours'
        ]
      },
      {
        id: 23,
        cardProportion: 127.5,
        imagePath: 'dark_chocolate_brownie.png',
        imagePathThumbnail: 'dark_chocolate_brownie.jpg',
        flash: 'new',
        tags: ['sweet-snacks', 'gluten-free', 'sugar-conscious', 'vegetarian'],
        productName: 'Dark Chocolate Fudge Brownie',
        description: 'The Simple Truth Dark Chocolate Fudge Brownie is the perfect gluten free treat and has reduced sugar.',
        nutritionalInfo: ['Reduced sugar',
          'Source of fibre',
          'No artificial colours or flavours',
          'Wheat free',
          'Ovo-vegetarian'
        ]
      },
      {
        id: 24,
        cardProportion: 127.5,
        imagePath: 'date_balls_apple_pecan_chia.png',
        imagePathThumbnail: 'date_balls_apple_pecan_chia.jpg',
        flash: 'new',
        tags: ['vegan', 'raw', 'sugar-conscious'],
        productName: 'Apple, Pecan & Chia Date Balls',
        description: 'Simple Truth Apple, Pecan & Chia Date Balls are tasty, vegan and made with no added sugar.',
        nutritionalInfo: ['Raw',
          'No added preservatives',
          'No added sugar',
          'High in fibre',
          'No artificial colours or flavours']
      },
      {
        id: 25,
        cardProportion: 127.5,
        imagePath: 'date_balls_coconut_macadamia.png',
        imagePathThumbnail: 'date_balls_coconut_macadamia.jpg',
        flash: 'new',
        tags: ['vegan', 'sweet-snacks', 'sugar-conscious'],
        productName: 'Coconut & Macadamia Date Balls',
        description: 'Simple Truth Coconut & Macadamia Date Balls are tasty, vegan and made with no added sugar.',
        nutritionalInfo: ['Raw',
          'No added preservatives',
          'No added sugar',
          'High in fibre',
          'No artificial colours or flavours']
      },
      {
        id: 26,
        cardProportion: 127.5,
        imagePath: 'date_balls_cranberry_beetroot_cashew.png',
        imagePathThumbnail: 'date_balls_cranberry_beetroot_cashew.jpg',
        flash: 'new',
        tags: ['vegan', 'raw', 'sweet-snacks'],
        productName: 'Cranberry, Beetroot & Cashew Date Balls',
        description: 'Simple Truth Cranberry, Beetroot & Cashew Date Balls are tasty, vegan and made with no added preservatives.',
        nutritionalInfo: ['Raw',
          'No added preservatives',
          'Source of fibre',
          'No artificial colours or flavours'
        ]
      },
      {
        id: 27,
        cardProportion: 127.5,
        imagePath: 'elbow_macaroni.png',
        imagePathThumbnail: 'elbow_macaroni.jpg',
        flash: 'new',
        tags: ['essentials', 'gluten-free', 'vegan', 'gmo-free'],
        productName: 'New Simple Truth Elbow Macaroni',
        description: 'Make your next meal a feast with the help of our vegan Simple Truth Elbow Macaroni. This gluten free pasta is preservative and GMO free.',
        nutritionalInfo: ['GMO free', 'No added preservatives']
      },
      {
        id: 28,
        cardProportion: 127.5,
        imagePath: 'Flakes.png',
        imagePathThumbnail: 'Flakes.jpg',
        flash: 'new',
        tags: ['vegan', 'sugar-conscious', 'breakfast'],
        productName: 'Crushed Wholewheat Flakes ',
        description: 'What if we told you that you could enjoy wholewheat flakes without any compromise necessary? With the Simple Truth Crushed Wholewheat Flakes you can, thanks to them consisting of 30% less sugar, being high in B vitamins and vegan.',
        nutritionalInfo: ['Vegan', '30% reduced sugar', 'High in fibre', 'High in vitamin B1, B2 & B3', 'Source of iron', 'No added preservatives']
      },
      {
        id: 29,
        cardProportion: 127.5,
        imagePath: 'fruit_chutney.png',
        imagePathThumbnail: 'fruit_chutney.jpg',
        flash: 'new',
        tags: ['condiments-oils', 'vegan', 'sugar-conscious'],
        productName: 'Fruit Chutney',
        description: 'Simple Truth Fruit Chutney is vegan and is sweetened naturally with pears and dates. Find it in-store now.',
        nutritionalInfo: ['Reduced sugar',
          'No added MSG',
          'Sweetened naturally',
          'No artificial colours or flavours'
        ]
      },
      {
        id: 30,
        cardProportion: 127.5,
        imagePath: 'fruit_juice_apple.png',
        imagePathThumbnail: 'fruit_juice_apple.jpg',
        flash: 'new',
        tags: ['drinks'],
        productName: '100% APPLE JUICE',
        description: 'Simple Truth 100% Apple Juice is pressed and squeezed. This locally made juice is high in vitamin C and not made from concentrate.',
        nutritionalInfo: ['High in vitamin C',
          'Naturally colourant free',
          'No artificial flavours',
          'Locally made',
          'Not from concentrate'
        ]
      },
      {
        id: 31,
        cardProportion: 127.5,
        imagePath: 'fruit_juice_berry.png',
        imagePathThumbnail: 'fruit_juice_berry.jpg',
        flash: 'new',
        tags: ['drinks'],
        productName: '100% Fruit Juice Blend',
        description: 'Simple Truth Berry 100% Fruit Juice Blend is pressed and squeezed. This juice is produced locally and not made from concentrate.',
        nutritionalInfo: ['High in vitamin C',
          'Naturally colourant free',
          'No artificial flavours',
          'Locally made',
          'Not from concentrate'
        ]
      },
      {
        id: 32,
        cardProportion: 127.5,
        imagePath: 'fruit_juice_orange.png',
        imagePathThumbnail: 'fruit_juice_orange.jpg',
        flash: 'new',
        tags: ['drinks'],
        productName: '100% Orange Juice',
        description: 'Simple Truth 100% Orange Juice is pressed and squeezed. This locally made juice is high in vitamin C and not made from concentrate.',
        nutritionalInfo: ['High in vitamin C',
          'Naturally colourant free',
          'No artificial flavours',
          'Locally made',
          'Not from concentrate'
        ]
      },
      {
        id: 33,
        cardProportion: 127.5,
        imagePath: 'gums_mango.png',
        imagePathThumbnail: 'gums_mango.jpg',
        flash: 'new',
        tags: ['sugar-conscious', 'sweet-snacks', 'preservative-free'],
        productName: 'Mango Fruit Gums',
        description: 'Simple Truth Mango Fruit Gums are made with mostly real fruit and contain no added sugar. These gums are very high in vitamin C and are a source of fibre.',
        nutritionalInfo: ['Made with 99% real fruit',
          'Preservative free',
          'No added sugar',
          'Source of fibre',
          'Very high in vitamin C']
      },
      {
        id: 34,
        cardProportion: 127.5,
        imagePath: 'jam_apricot.png',
        imagePathThumbnail: 'jam_apricot.jpg',
        flash: 'new',
        tags: ['essentials', 'sugar-conscious', 'preservative-free'],
        productName: 'Apricot Extra Fruit Jam',
        description: 'Enjoy a sweet treat without the guilt when you try the Simple Truth Apricot Extra Fruit Jam. It’s made with less sugar and contains no preservatives.',
        nutritionalInfo: ['Reduced sugar', 'Preservative free']
      },
      {
        id: 35,
        cardProportion: 127.5,
        imagePath: 'jam_strawberry.png',
        imagePathThumbnail: 'jam_strawberry.jpg',
        flash: 'new',
        tags: ['essentials', 'sugar-conscious', 'preservative-free'],
        productName: 'Strawberry Extra Fruit Jam',
        description: 'Indulge in a classic without the added sugar! The Simple Truth Strawberry Extra Fruit Jam is free from preservatives and has less sugar.',
        nutritionalInfo: ['Reduced sugar', 'Preservative free']
      },
      {
        id: 36,
        cardProportion: 127.5,
        imagePath: 'jam-mixed-berry.png',
        imagePathThumbnail: 'jam-mixed-berry.jpg',
        flash: 'new',
        tags: ['essentials', 'sugar-conscious', 'preservative-free'],
        productName: 'Simple Truth Mixed Berry Extra Fruit Jam ',
        description: 'Our Simple Truth Mixed Berry Extra Fruit Jam is free from preservatives and has less sugar, making it the ideal choice for healthier eating habits.',
        nutritionalInfo: ['Reduced sugar', 'Preservative free']
      },
      {
        id: 37,
        cardProportion: 127.5,
        imagePath: 'mexican_bowl.png',
        imagePathThumbnail: 'mexican_bowl.jpg',
        flash: 'new',
        tags: ['vegetarian', 'meals'],
        productName: 'Mexican Bowl',
        description: 'Planning your next meal? The Simple Truth Mexican Bowl is a fresh and flavourful vegetarian dish. It’s not only delicious but a good source of fibre too.',
        nutritionalInfo: ['Source of fibre', 'No added preservatives']
      },
      {
        id: 38,
        cardProportion: 127.5,
        imagePath: 'noodles_moringa.png',
        imagePathThumbnail: 'noodles_moringa.jpg',
        flash: 'new',
        tags: ['vegan'],
        productName: 'Moringa Noodles',
        description: 'Stock your pantry with these delicious vegan Simple Truth Moringa Noodles. They have a unique flavour combined with the health benefits of moringa.',
        nutritionalInfo: ['No added preservatives', 'Source of fibre', 'GMO free']
      },
      {
        id: 39,
        cardProportion: 127.5,
        imagePath: 'noodles_purple_sweet_potato.png',
        imagePathThumbnail: 'noodles_purple_sweet_potato.jpg',
        flash: 'new',
        tags: ['vegan'],
        productName: 'Purple Sweet Potato Noodles',
        description: 'Few things compare to the complexity of the vegan Simple Truth Purple Sweet Potato Noodles. They will transform any pasta dish from bland to extraordinary.',
        nutritionalInfo: ['No added preservatives', 'Source of fibre', 'GMO free']
      },
      {
        id: 40,
        cardProportion: 127.5,
        imagePath: 'orange_marmalade.png',
        imagePathThumbnail: 'orange_marmalade.jpg',
        flash: 'new',
        tags: ['essentials', 'sugar-conscious', 'preservative-free'],
        productName: 'Orange Marmalade',
        description: 'Enjoy a taste of nostalgia with reduced sugar, thanks to the Simple Truth Orange Marmalade. It’s delicious and contains no preservatives.',
        nutritionalInfo: ['Reduced sugar', 'Preservative free']
      },
      {
        id: 41,
        cardProportion: 127.5,
        imagePath: 'orange-raspberry.png',
        imagePathThumbnail: 'orange-raspberry.jpg',
        flash: 'new',
        tags: ['drinks', 'sugar-free', 'preservative-free'],
        productName: 'Sparkling Orange & Raspberry Flavoured Drink',
        description: 'Simple Truth Sparkling Orange & Raspberry Flavoured Drink is sugar free and made with natural spring water.',
        nutritionalInfo: ['Made with natural spring water',
          'Preservative free',
          'No artificial colours or flavours']
      },
      {
        id: 42,
        cardProportion: 127.5,
        imagePath: 'peanut_butter_blondie.png',
        imagePathThumbnail: 'peanut_butter_blondie.jpg',
        flash: 'new',
        tags: ['sweet-snacks'],
        productName: 'Peanut Butter Blondie',
        description: 'A Simple Truth Peanut Butter Blondie is the ultimate treat! It is gluten free and is made with less sugar.',
        nutritionalInfo: ['Reduced sugar',
          'Source of fibre',
          'No artificial colours or flavours',
          'Wheat free',
          'Lacto-ovo vegetarian']
      },
      {
        id: 43,
        cardProportion: 127.5,
        imagePath: 'peanut_butter_crunchy.png',
        imagePathThumbnail: 'peanut_butter_crunchy.jpg',
        flash: 'new',
        tags: ['sugar-free', 'sugar-conscious', 'high-protein'],
        productName: 'Crunchy Peanut Butter',
        description: 'Find the Simple Truth Crunchy Peanut Butter in-store now for the perfect guilt-free treat. It contains no added sugar or salt.',
        nutritionalInfo: ['Nothing but peanuts',
          'Preservative free',
          'No added sugar or salt']
      },
      {
        id: 44,
        cardProportion: 127.5,
        imagePath: 'peanut_butter_protien_balls.png',
        imagePathThumbnail: 'peanut_butter_protien_balls.jpg',
        flash: 'new',
        tags: ['high-protein', 'sweet-snacks', 'vegetarian', 'sugar-conscious'],
        productName: 'Peanut Butter Protein Balls ',
        description: 'Simple Truth Peanut Butter Protein Balls are high in protein, a source of fibre and taste delicious too! These protein balls have no added sugar and are available in-store.',
        nutritionalInfo: ['No added preservatives',
          'No added sugar',
          'High in protein',
          'Lacto-vegetarian',
          'Source of fibre']
      },
      {
        id: 45,
        cardProportion: 127.5,
        imagePath: 'peanut_butter_smooth.png',
        imagePathThumbnail: 'peanut_butter_smooth.jpg',
        flash: 'new',
        tags: ['no-sugar', 'sugar-conscious', 'high-protein'],
        productName: 'Smooth Peanut Butter',
        description: 'The Simple Truth Smooth Peanut Butter contains no added sugar or salt which means that every spoonful is guilt-free indulgence.',
        nutritionalInfo: ['Nothing but peanuts',
          'Preservative free',
          'No added sugar or salt']
      },
      {
        id: 46,
        cardProportion: 127.5,
        imagePath: 'pomegranate.png',
        imagePathThumbnail: 'pomegranate.jpg',
        flash: 'new',
        tags: ['drinks', 'sugar-free', 'preservative-free'],
        productName: 'Sparkling Pomegranate & Hibiscus Flavoured Drink',
        description: 'Simple Truth Sparkling Pomegranate & Hibiscus Flavoured Drink is made with natural spring water and is sugar free.',
        nutritionalInfo: ['Made with natural spring water',
          'Preservative free',
          'No artificial colours or flavours']
      },
      {
        id: 47,
        cardProportion: 127.5,
        imagePath: 'pretzel_knots.png',
        imagePathThumbnail: 'pretzel_knots.jpg',
        flash: 'new',
        tags: ['gluten-free', 'vegan', 'snacks', 'preservative-free'],
        productName: 'Lightly Salted Pretzel Knots ',
        description: 'Make snacking even tastier with Simple Truth Lightly Salted Pretzel Knots. These pretzels are gluten free, vegan and baked, not fried.',
        nutritionalInfo: ['Gluten free',
          'Vegan',
          'Baked not fried',
          'No added preservatives',
          'Source of fibre']
      },
      {
        id: 48,
        cardProportion: 127.5,
        imagePath: 'protein_balls_cocoa_almont.png',
        imagePathThumbnail: 'protein_balls_cocoa_almont.jpg',
        flash: 'new',
        tags: ['high-protein', 'sweet-snacks', 'sugar-conscious', 'vegetarian'],
        productName: 'Cocoa & Almond Protein Balls',
        description: 'Simple Truth Cocoa & Almond Protein Balls are high in protein, a source of fibre and taste delicious too! These protein balls have no added sugar and are available in-store now.',
        nutritionalInfo: ['No added preservatives',
          'No added sugar',
          'High in protein',
          'Lacto-vegetarian',
          'Source of fibre',
          'No artificial colours or flavours']
      },
      {
        id: 49,
        cardProportion: 127.5,
        imagePath: 'protein_balls_very_bery.png',
        imagePathThumbnail: 'protein_balls_very_bery.jpg',
        flash: 'new',
        tags: ['high-protein', 'sweet-snacks', 'vegetarian'],
        productName: 'Very Berry Protein Balls',
        description: 'Simple Truth Very Berry Protein Balls are high in protein, a source of fibre and taste delicious too! These protein balls have no added preservatives and are available in-store now.',
        nutritionalInfo: ['No added preservatives',
          'High in protein',
          'Lacto-vegetarian',
          'Source of fibre',
          'No artificial colours or flavours']
      },
      {
        id: 50,
        cardProportion: 127.5,
        imagePath: 'raw_honey.png',
        imagePathThumbnail: 'raw_honey.jpg',
        flash: 'new',
        tags: ['raw'],
        productName: 'Raw Honey',
        description: 'The Simple Truth Raw Honey is sourced locally and is completely unheated and unfiltered. Try it today to discover its natural sweetness and satisfying flavour.',
        nutritionalInfo: ['100% pure', 'Unheated & unfiltered', 'Locally sourced']
      },
      {
        id: 51,
        cardProportion: 127.5,
        imagePath: 'red_alaea_sea_salt.jpg',
        imagePathThumbnail: 'red_alaea_sea_salt.jpg',
        flash: 'new',
        tags: ['organic'],
        productName: 'Red Alaea Sea Salt',
        description: 'Simple Truth Red Alaea Sea Salt is 100% natural and is made with unrefined sea salt and purified red Hawaiian clay.',
        nutritionalInfo: ['100% pure', 'Unrefined salt']
      },
      {
        id: 52,
        cardProportion: 127.5,
        imagePath: 'roll_apricot_butternut.png',
        imagePathThumbnail: 'roll_apricot_butternut.jpg',
        flash: 'new',
        tags: ['sugar-conscious', 'preservative-free', 'sweet-snacks'],
        productName: 'Apricot & Butternut Roll',
        description: 'The Simple Truth Apricot & Butternut Roll is made with only fruit and vegetables. This nutritious and tasty snack is very high in vitamin C and contains no added sugar.',
        nutritionalInfo: ['Sulphur free',
          '100% fruit & veg',
          'Very high in vitamin C',
          'No added sugar',
          'Preservative free',
          'No artificial colours or flavours']
      },
      {
        id: 53,
        cardProportion: 127.5,
        imagePath: 'roll_very_berry.png',
        imagePathThumbnail: 'roll_very_berry.jpg',
        flash: 'new',
        tags: ['sugar-conscious', 'preservative-free', 'sweet-snacks'],
        productName: 'Very Berry Roll',
        description: 'The Simple Truth Very Berry Roll is made with only fruit and is very high in vitamin C. This delicious snack contains no added sugar and is high in fibre.',
        nutritionalInfo: ['Sulphur free',
          '100% fruit',
          'Very high in vitamin C',
          'No added sugar',
          'Preservative free',
          'No artificial colours or flavours']
      },
      {
        id: 54,
        cardProportion: 127.5,
        imagePath: 'rub_chipotle.png',
        imagePathThumbnail: 'rub_chipotle.jpg',
        flash: 'new',
        tags: ['preservative-free', 'condiments-oils'],
        productName: 'Chipotle Rub',
        description: 'The Simple Truth Chipotle Rub is fantastic for a wide selection of dishes thanks to its unique flavour. Find this rub in-store now! ',
        nutritionalInfo: ['Non-irradiated',
          'No added MSG',
          'No added preservatives',
          'Made with sea salt']
      },
      {
        id: 55,
        cardProportion: 127.5,
        imagePath: 'rub_garlic_herb.png',
        imagePathThumbnail: 'rub_garlic_herb.jpg',
        flash: 'new',
        tags: ['preservative-free', 'condiments-oils'],
        productName: 'Greek Garlic & Herb Rub',
        description: 'You can’t go wrong with our Simple Truth Greek Garlic & Herb Rub. Consider it your secret weapon in the kitchen – and it contains no added MSG or added preservatives.',
        nutritionalInfo: ['Non-irradiated',
          'No added MSG',
          'No added preservatives',
          'Made with sea salt']
      },
      {
        id: 56,
        cardProportion: 127.5,
        imagePath: 'rub_italian.png',
        imagePathThumbnail: 'rub_italian.jpg',
        flash: 'new',
        tags: ['condiments-oils', 'preservative-free'],
        productName: 'Italian Rub',
        description: 'Transport your senses and cooking to Italy with the Simple Truth Italian Rub. It is made with no added MSG or preservatives.',
        nutritionalInfo: ['Non-irradiated',
          'No added MSG',
          'No added preservatives',
          'Made with sea salt']
      },
      {
        id: 57,
        cardProportion: 127.5,
        imagePath: 'rub_steak_house.png',
        imagePathThumbnail: 'rub_steak_house.jpg',
        flash: 'new',
        tags: ['condiments-oils', 'preservative-free'],
        productName: 'Steakhouse Rub',
        description: 'Cook steak like never before when you make use of the Simple Truth Steakhouse Rub. It is made with sea salt and contains no preservatives.',
        nutritionalInfo: ['Non-irradiated',
          'No added MSG',
          'No added preservatives',
          'Made with sea salt']
      },
      {
        id: 58,
        cardProportion: 127.5,
        imagePath: 'rub_sweet_spicy_bbq.png',
        imagePathThumbnail: 'rub_sweet_spicy_bbq.jpg',
        flash: 'new',
        tags: ['condiments-oils', 'preservative-free'],
        productName: 'Sweet & Spicy BBQ Rub',
        description: 'The Simple Truth Sweet & Spicy BBQ Rub is a crowd-pleaser! Perfect for adding flavour to your braai meats or roasted chicken dishes.',
        nutritionalInfo: ['Non-irradiated',
          'No added MSG',
          'No added preservatives',
          'Made with sea salt']
      },
      {
        id: 59,
        cardProportion: 127.5,
        imagePath: 'salt_cypriot.png',
        imagePathThumbnail: 'salt_cypriot.jpg',
        flash: 'new',
        tags: ['organic', 'condiments-oils'],
        productName: 'Cypriot Salt',
        description: 'Simple Truth Cypriot Salt is unrefined and hand harvested.',
        nutritionalInfo: ['100% pure',
          'Unrefined salt', 'Hand harvested']
      }, {
        id: 60,
        cardProportion: 127.5,
        imagePath: 'salt_hawaiian_black.png',
        imagePathThumbnail: 'salt_hawaiian_black.jpg',
        flash: 'new',
        tags: ['organic', 'condiments-oils'],
        productName: 'Hawaiian Black Salt',
        description: 'With the Simple Truth Hawaiian Black Salt, every recipe will have great flavour. It is made with unrefined salt and activated charcoal from coconut shells.',
        nutritionalInfo: ['100% pure', 'Unrefined salt']
      },
      {
        id: 61,
        cardProportion: 127.5,
        imagePath: 'salt_persian_blue.png',
        imagePathThumbnail: 'salt_persian_blue.jpg',
        flash: 'new',
        tags: ['organic', 'condiments-oils'],
        productName: 'Persian Blue Salt',
        description: 'Simple Truth Persian Blue Salt is unrefined and now available in-store.',
        nutritionalInfo: ['100% pure', 'Unrefined salt']
      },
      {
        id: 62,
        cardProportion: 127.5,
        imagePath: 'seed_crackers_garlic_herb.png',
        imagePathThumbnail: 'seed_crackers_garlic_herb.jpg',
        flash: 'new',
        tags: ['gluten-free', 'vegan', 'snacks', 'preservative-free'],
        productName: 'Garlic & Herb Seed Crackers',
        description: 'Simple Truth Garlic & Herb Seed Crackers are vegan and high in fibre.',
        nutritionalInfo: ['Gluten free',
          'Vegan',
          'No added preservatives',
          'High in fibre']
      },
      {
        id: 63,
        cardProportion: 127.5,
        imagePath: 'seed_crackers.png',
        imagePathThumbnail: 'seed_crackers.jpg',
        flash: 'new',
        tags: ['gluten-free', 'vegan', 'snacks', 'preservative-free'],
        productName: 'Spicy BBQ Seed Crackers',
        description: 'Simple Truth Spicy BBQ Seed Crackers are vegan and high in fibre.',
        nutritionalInfo: ['Gluten free',
          'Vegan',
          'No added preservatives',
          'High in fibre']
      },
      {
        id: 64,
        cardProportion: 127.5,
        imagePath: 'ST_All-Purpose-Cleaner_01.png',
        imagePathThumbnail: 'ST_All-Purpose-Cleaner_01.jpg',
        flash: 'new',
        tags: ['eco-friendly'],
        productName: 'Multi Purpose Cleaner',
        description: 'Simple Truth Multi Purpose Cleaner is an eco friendly household essential. This cruelty free product is made from naturally derived cleaning ingredients and is paraben free.',
        nutritionalInfo: ['Eco Friendly',
          'Biodegradable',
          'Cruelty free',
          'No artificial colours',
          'Paraben free',
          'Naturally derived cleaning ingredients'
        ]
      },
      {
        id: 65,
        cardProportion: 127.5,
        imagePath: 'ST_Chickpea_Bowl.png',
        imagePathThumbnail: 'ST_Chickpea_Bowl.jpg',
        flash: 'new',
        tags: ['vegan', 'meals'],
        productName: 'Chickpea & Quinoa Bowl',
        description: 'The Simple Truth Chickpea & Quinoa Bowl is deliciously satisfying and a great source of protein too. Treat your senses to perfectly balanced flavours of this bowl, which has no added MSG.',
        nutritionalInfo: ['Source of fibre', 'No added preservatives']
      },
      {
        id: 66,
        cardProportion: 127.5,
        imagePath: 'ST_Laundry-Liquid_01.png',
        imagePathThumbnail: 'ST_Laundry-Liquid_01.jpg',
        flash: 'new',
        tags: ['eco-friendly'],
        productName: 'Laundry Liquid Concentrate ',
        description: 'Simple Truth Laundry Liquid Concentrate is not only a cruelty free product, but effectively cleans. It is made from naturally derived cleaning ingredients and contains no dyes.',
        nutritionalInfo: ['Eco friendly',
          'Biodegradable',
          'Cruelty free',
          'Naturally derived cleaning ingredients',
          'No dyes',
          'No phosphate or optical brighteners',
          'Paraben free'
        ]
      },
      {
        id: 67,
        cardProportion: 127.5,
        imagePath: 'ST_Mediterranean_Bowl.png',
        imagePathThumbnail: 'ST_Mediterranean_Bowl.jpg',
        flash: 'new',
        tags: ['vegan', 'meals'],
        productName: 'Mediterranean Bowl',
        description: 'If you’re looking for a taste of Mediterranean cuisine with added convenience, try our vegan Simple Truth Mediterranean Bowl.',
        nutritionalInfo: ['Source of fibre', 'No added preservatives']
      },
      {
        id: 68,
        cardProportion: 127.5,
        imagePath: 'ST_Roasted_Veggie_Bowl.png',
        imagePathThumbnail: 'ST_Roasted_Veggie_Bowl.jpg',
        flash: 'new',
        tags: ['vegan', 'meals'],
        productName: 'Roasted Veggie Bowl',
        description: 'Not many things compare to the sheer comfort of roasted vegetables, and our Simple Truth Roasted Veggie Bowl is packed with flavour and has no added MSG. ',
        nutritionalInfo: ['Source of fibre', 'No added preservatives']
      },
      {
        id: 69,
        cardProportion: 127.5,
        imagePath: 'noodles_moringa.png',
        imagePathThumbnail: 'noodles_moringa.jpg',
        flash: 'new',
        tags: ['vegan', 'vegetarian', 'gmo-free', 'essentials'],
        productName: 'Moringa Noodles',
        description: 'Stock your pantry with these delicious vegan Simple Truth Moringa Noodles. They have a unique flavour combined with the health benefits of moringa.',
        nutritionalInfo: ['No added preservatives',
          'Source of fibre',
          'GMO free'
        ]
      },
      {
        id: 70,
        cardProportion: 127.5,
        imagePath: 'ST-Almond.png',
        imagePathThumbnail: 'ST-Almond.jpg',
        flash: 'new',
        tags: ['vegan', 'vegetarian', 'essentials', 'gmo-free'],
        productName: 'Turmeric Noodles ',
        description: 'Stock your pantry with these delicious vegan Simple Truth Turmeric Noodles today. They have great flavour combined with the health benefits of turmeric.',
        nutritionalInfo: ['No added preservatives',
          'Source of fibre',
          'GMO free'
        ]
      },
      {
        id: 71,
        cardProportion: 127.5,
        imagePath: 'noodles_purple_sweet_potato.png',
        imagePathThumbnail: 'noodles_purple_sweet_potato.jpg',
        flash: 'new',
        tags: ['vegan', 'vegetarian', 'gmo-free', 'essentials'],
        productName: 'Purple Sweet Potato Noodles',
        description: 'Few things compare to the complexity of the vegan Simple Truth Purple Sweet Potato Noodles. They will transform any pasta dish from bland to extraordinary.',
        nutritionalInfo: ['No added preservatives',
          'Source of fibre',
          'GMO free'
        ]
      },
      {
        id: 72,
        cardProportion: 127.5,
        imagePath: 'raw_honey.png',
        imagePathThumbnail: 'raw_honey.jpg',
        flash: 'new',
        tags: ['raw', 'essentials'],
        productName: 'Raw Honey',
        description: 'The Simple Truth Raw Honey is sourced locally and is completely unheated and unfiltered. Try it today to discover its natural sweetness and satisfying flavour.',
        nutritionalInfo: ['100% pure', 'Unheated & unfiltered', 'Locally sourced']
      },
      {
        id: 73,
        cardProportion: 127.5,
        imagePath: 'peanut_butter_crunchy.png',
        imagePathThumbnail: 'peanut_butter_crunchy.jpg',
        flash: 'new',
        tags: ['sugar-conscious', 'preservative-free', 'essentials'],
        productName: 'Crunchy Peanut Butter',
        description: 'Find the Simple Truth Crunchy Peanut Butter in-store now for the perfect guilt-free treat. It contains no added sugar or salt.',
        nutritionalInfo: ['Nothing but peanuts',
          'Preservative free',
          'No added sugar or salt'
        ]
      },
      {
        id: 74,
        cardProportion: 127.5,
        imagePath: 'peanut_butter_smooth.png',
        imagePathThumbnail: 'peanut_butter_smooth.jpg',
        flash: 'new',
        tags: ['sugar-conscious', 'preservative-free', 'essentials'],
        productName: 'Smooth Peanut Butter',
        description: 'The Simple Truth Smooth Peanut Butter contains no added sugar or salt which means that every spoonful is guilt-free indulgence.',
        nutritionalInfo: ['Nothing but peanuts',
          'Preservative free',
          'No added sugar or salt'
        ]
      },
      {
        id: 75,
        cardProportion: 127.5,
        imagePath: 'apple_cider_vinegar.png',
        imagePathThumbnail: 'apple_cider_vinegar.jpg',
        flash: 'new',
        tags: ['organic', 'raw', 'essentials'],
        productName: 'Raw & Unfiltered Apple Cider Vinegar',
        description: 'Simple Truth Raw & Unfiltered Apple Cider Vinegar is a must-have in every home. This versatile product is organic, raw and contains nothing but apples.',
        nutritionalInfo: ['100% natural',
          'Nothing but apples',
          'Unpasteurised',
          'Organic',
          'Raw',
          'Unfiltered'
        ]
      },
      {
        id: 76,
        cardProportion: 127.5,
        imagePath: 'coconut_sugar.png',
        imagePathThumbnail: 'coconut_sugar.jpg',
        flash: 'new',
        tags: ['organic', 'essentials', 'gmo-free'],
        productName: 'Coconut Sugar',
        description: 'Once you enjoy the taste of our organic Simple Truth Coconut Sugar, it will be difficult to choose any other product! It is made from 100% natural ingredients and contains no preservatives.',
        nutritionalInfo: ['Made from the golden nectar of coconut tree blossoms',
          '100% natural & sustainable',
          'Unrefined',
          'Non-GMO',
          'Preservative free'
        ]
      },
      {
        id: 77,
        cardProportion: 127.5,
        imagePath: 'ST-Rub.png',
        imagePathThumbnail: 'ST-Rub.jpg',
        flash: 'new',
        tags: ['condiments-oils', 'preservative-free'],
        productName: 'Roast Chicken Rub',
        description: 'Elevate your next chicken dish with the Simple Truth Roast Chicken Rub. It is made with sea salt and contains no added MSG.',
        nutritionalInfo: ['Non-irradiated', 'No added MSG', 'No added preservatives', 'Made with sea salt']
      },
      {
        id: 78,
        cardProportion: 127.5,
        imagePath: 'ST-FabricSoftner.png',
        imagePathThumbnail: 'ST-FabricSoftner.jpg',
        flash: 'new',
        tags: ['eco-friendly'],
        productName: 'Fabric Softener Concentrate',
        description: 'Simple Truth Fabric Softener Concentrate is an eco friendly household essential. This cruelty free product is made from naturally derived cleaning ingredients and contains no artificial colours.',
        nutritionalInfo: ['Eco Friendly',
          'Biodegradable',
          'Cruelty free',
          'Naturally derived cleaning ingredients',
          'No artificial colours',
          'Paraben free'
        ]
      },
      {
        id: 79,
        cardProportion: 127.5,
        imagePath: 'ST-Dishwashing-Liquid.png',
        imagePathThumbnail: 'ST-Dishwashing-Liquid.jpg',
        flash: 'new',
        tags: ['eco-friendly'],
        productName: 'Dishwashing Liquid',
        description: 'Simple Truth Dishwashing Liquid is an eco friendly kitchen essential. This cruelty free product is made from naturally derived cleaning ingredients and contains no artificial colours.',
        nutritionalInfo: ['Eco Friendly',
          'Biodegradable',
          'Cruelty free',
          'Naturally derived cleaning ingredients',
          'No artificial colours',
          'Paraben free'
        ]
      },
      {
        id: 80,
        cardProportion: 127.5,
        imagePath: 'ST-MultiPurpose.png',
        imagePathThumbnail: 'ST-MultiPurpose.jpg',
        flash: 'new',
        tags: ['eco-friendly'],
        productName: 'All Purpose Cleaner',
        description: 'Simple Truth All Purpose Cleaner is an eco friendly kitchen essential. This cruelty free product is made from naturally derived cleaning ingredients and contains no artificial colours.',
        nutritionalInfo: ['Eco Friendly',
          'Biodegradable',
          'Cruelty free',
          'Naturally derived cleaning ingredients',
          'No artificial colours',
          'Paraben free'
        ]
      },
      {
        id: 81,
        cardProportion: 127.5,
        imagePath: 'gums_mixed_berry.png',
        imagePathThumbnail: 'gums_mixed_berry.jpg',
        flash: 'new',
        tags: ['sugar-conscious', 'sweet-snacks', 'preservative-free'],
        productName: 'Mixed Berry Fruit Gums',
        description: 'Simple Truth Mixed Berry Fruit Gums are made with mostly real fruit and contain no added sugar. These gums are very high in vitamin C and are a source of fibre. ',
        nutritionalInfo: ['Made with 99% real fruit',
          'Preservative free',
          'No added sugar',
          'Source of fibre',
          'Very high in vitamin C']
      },
      {
        id: 82,
        cardProportion: 127.5,
        imagePath: 'tomato_sauce.png',
        imagePathThumbnail: 'tomato_sauce.jpg',
        flash: 'new',
        tags: ['sugar-conscious', 'condiments-oils', 'preservative-free'],
        productName: 'Tomato Sauce',
        description: 'The Simple Truth Tomato Sauce is great tasting and is made with reduced sugar and sodium. Get this family-favourite sauce in-store now.',
        nutritionalInfo: ['Reduced sugar',
          'Reduced sodium',
          'No thickeners',
          'No added preservatives',
          'No added colours or flavours'
        ]
      }
    ],

    sideDrawerOpen: false,
    sideDrawerId: 2,
    videoId: 'pga8mV8LJnE'
  },
  mutations: {
    openDrawer(_state, _payload) {
      _state.sideDrawerOpen = true;
      _state.sideDrawerId = _payload.id;
      _state.videoId = _payload.videoLink;
    },
    closeDrawer(_state) {
      _state.sideDrawerOpen = false;
    },
    updateVideoId(_state, _id) {
      _state.videoId = _id;
    }
  },
  getters: {
    sideDrawerState(_state) {
      return _state.sideDrawerOpen;
    },
    sideDrawerId(_state) {
      return _state.sideDrawerId;
    },
    sideDrawerCard(_state) {
      return _state.productCards[_state.sideDrawerId - 1];
    },
    videoId(_state) {
      return _state.videoId;
    }
  },
  actions: {}
})
